// Auto-generated by axfetchum. Do not edit.

import type { CreateProjectRequest } from "./CreateProjectRequest";
import type { ProjectListItem } from "./ProjectListItem";
import type { ProjectMeta } from "./ProjectMeta";

export class ApiError extends Error {
  constructor(message: string, public status: number, public body?: unknown) {
    super(message);
    this.name = "ApiError";
  }
}

export interface ClientOptions {
  baseUrl: string;
  getToken?: () => Promise<string | null>;
  credentials?: RequestCredentials;
  fetch?: typeof fetch;
  onError?: (error: ApiError) => void;
}

type RequestOptions = {
  method?: string;
  body?: unknown;
  query?: Record<string, unknown>;
  auth?: boolean;
};

function createRequest(options: ClientOptions) {
  const { baseUrl, credentials = "same-origin" } = options;
  async function request<T>(
    path: string,
    opts: RequestOptions = {},
  ): Promise<T> {
    const { method = "GET", body, query, auth } = opts;
    // Resolve fetch at call time (not at client creation) so OTel
    // instrumentation patches are picked up even when the client
    // module is imported before telemetry initializes.
    const fetchFn = options.fetch ?? globalThis.fetch;

    let url = `${baseUrl}${path}`;
    if (query) {
      const params = new URLSearchParams();
      for (const [key, value] of Object.entries(query)) {
        if (value !== undefined && value !== null) {
          params.set(key, String(value));
        }
      }
      const qs = params.toString();
      if (qs) url += `?${qs}`;
    }

    const headers: Record<string, string> = { "Content-Type": "application/json" };

    if (auth && options.getToken) {
      const token = await options.getToken();
      if (token) headers.Authorization = `Bearer ${token}`;
    }

    const response = await fetchFn(url, {
      method,
      credentials,
      headers,
      body: body ? JSON.stringify(body) : undefined,
    });

    if (!response.ok) {
      const text = await response.text();
      let message: string;
      let errorBody: unknown;
      try {
        const json = JSON.parse(text);
        message = json.error ?? json.message ?? text;
        errorBody = json;
      } catch {
        message = text;
      }
      const error = new ApiError(message, response.status, errorBody);
      if (options.onError) options.onError(error);
      throw error;
    }

    const text = await response.text();
    return (text ? JSON.parse(text) : undefined) as T;
  }

  return request;
}

export function createStoryorClient(options: ClientOptions) {
  const request = createRequest(options);

  return {
    projects: {
      projectsList: () => request<ProjectListItem[]>("/api/projects"),
      projectsCreate: (body: CreateProjectRequest) =>
        request<ProjectMeta>("/api/projects", { method: "POST", body }),
      projectsGet: (id: string) =>
        request<ProjectMeta>(`/api/projects/${id}`),
      projectsDelete: (id: string) =>
        request<void>(`/api/projects/${id}`, { method: "DELETE" }),
    },
  };
}

export type StoryorClient = ReturnType<typeof createStoryorClient>;
