// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 创建项目的请求体
 */
export type CreateProjectRequest = { 
/**
 * 项目名称
 */
name: string, 
/**
 * 原始小说文本
 */
novel_text: string, };
