// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 统一错误响应体（所有 4xx/5xx 返回此结构）
 */
export type ErrorResponse = { 
/**
 * 错误消息（人类可读）
 */
error: string, };
