// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 健康检查响应
 */
export type HealthResponse = { 
/**
 * 服务名称
 */
service: string, 
/**
 * 版本号
 */
version: string, 
/**
 * 工作区目录
 */
workspace: string, };
