// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectPhase } from "./ProjectPhase";

/**
 * 项目元信息（持久化到 `project.json`）
 */
export type ProjectMeta = { 
/**
 * 项目唯一 ID（UUID v4，同时作为目录名）
 */
id: string, 
/**
 * 项目名称（用户可读）
 */
name: string, 
/**
 * 原始小说文本文件的相对路径（相对于项目目录）
 */
novel_path: string, 
/**
 * 创建时间（UTC）
 */
created_at: string, 
/**
 * 当前所处阶段
 */
current_phase: ProjectPhase, 
/**
 * 原始小说字符数
 */
novel_chars: number, };
