// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 四阶段流水线的阶段标识
 */
export type ProjectPhase = "created" | "preprocessing" | "scripting" | "voicedesigning" | "synthesizing" | "completed";
