// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectPhase } from "./ProjectPhase";

/**
 * 项目列表条目（不含大体积产物，仅元信息）
 */
export type ProjectListItem = { id: string, name: string, created_at: string, current_phase: ProjectPhase, novel_chars: number, };
